### ISSUE TITLE
AssertionError on v3.3

### ISSUE THREAD

**Issue by defendant602** [Magdoll/SQANTI2#23]
Hi , Liz:

 I am running sqanti_qc2.py on version 3.3, and my commands are like this:
`python sqanti_qc2.py --aligner_choice gmap -x Gbarbadense -t 20 --geneid all.collapsed.rep.fa genome.gtf genome.fa -o test`

In my STDERR, I get this Error :

output written to all.collapsed.rep.renamed_corrected.fasta
**** Parsing Isoforms....
Traceback (most recent call last):
  File "/export/pipeline/RNASeq/Software/SQANTI2/V3.3/SQANTI2-master/sqanti_qc2.py", line 1746, in <module>
    main()
  File "/export/pipeline/RNASeq/Software/SQANTI2/V3.3/SQANTI2-master/sqanti_qc2.py", line 1742, in main
    run(args)
  File "/export/pipeline/RNASeq/Software/SQANTI2/V3.3/SQANTI2-master/sqanti_qc2.py", line 1389, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/export/pipeline/RNASeq/Software/SQANTI2/V3.3/SQANTI2-master/sqanti_qc2.py", line 387, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/export/pipeline/RNASeq/Software/cDNA_Cupcake/v8.0/cDNA_Cupcake/cupcake/io/GFF.py", line 393, in next
    return self.read()            
  File "/export/pipeline/RNASeq/Software/cDNA_Cupcake/v8.0/cDNA_Cupcake/cupcake/io/GFF.py", line 550, in read
    assert raw[2] == 'transcript'
AssertionError

And in one of the output files "all.collapsed.rep.renamed_corrected.gtf" , the third column only contains "exon", but no "transcript".

Would you please kindly check this error out? Thanks a lot.
Feng

**Comment by Magdoll** [comment]
Hi @defendant602 ,

I am aware of this issue and this is becuz of several dependency updates.

1. Please update to SQANTI2 v3.5
2. Please update Cupcake to v8.1
3. Please install gffread and gtfToGenePred using BioConda

```
conda install -n anaCogent3 -c bioconda ucsc-gtftogenepred openssl=1.0
conda install -n anaCogent3 -c bioconda gffread
```
