### ISSUE TITLE
subprocess.CalledProcessError in PERL

### ISSUE THREAD

**Issue by yzhang88** [Magdoll/SQANTI2#30]
Hi Elizabeth,

I had an error (subprocess.CalledProcessError) with SQANTI2 (v2.8) when I am in "Predicting ORF" step, and it is strange that this error just happened in one of my samples (other data could get the classification result). 

Here is the log:
```R scripting front-end version 3.5.1 (2018-07-02)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /DATA/test_OC_1
_2/collapse/OC_1_2.collapsed.rep.renamed.fasta
Error corrected FASTA /DATA/test_OC_1_2/annotation/OC_1_2
.collapsed.rep.renamed_corrected.fasta already exists. Using it...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Use of uninitialized value in open at /DATA/software/SQANTI2/utilities/gmst/gmst.pl line 885, <$FA> line 94.
**** Running SQANTI...
**** Parsing provided files....
Reading genome fasta /DATA/database/mm10/reference/mm10.sort.fa....
**** Predicting ORF sequences...
Traceback (most recent call last):
  File "/DATA/software/SQANTI2/sqanti_qc2.py", line 1599, in <module>
    main()
  File "/DATA/software/SQANTI2/sqanti_qc2.py", line 1595, in main
    run(args)
  File "/DATA/software/SQANTI2/sqanti_qc2.py", line 1248, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/DATA/software/SQANTI2/sqanti_qc2.py", line 480, in correctionPlusORF
pred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/DATA/anaconda2/envs/rna/lib/python2.7/subprocess.py", line 190, in c
heck_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /DATA/software/SQANTI2/utilities
/gmst/gmst.pl -faa --strand direct --fnn --output /DATA/t
est_OC_1_2/annotation/GMST/GMST_tmp /DATA/test_OC_1_2/annotation/OC_1_2.collapsed.rep.renamed_corrected.fasta' returned non-zero exit status 2
```
  
Thanks,
Y.Zhang

**Comment by Magdoll** [comment]
Hi @yzhang88 ,
The error comes from running GMST (which isn't SQANTI2) so it can be a little tricky to troubleshoot.

That said can you please update SQANTI2 to the latest version and re-run the results in a clean directory? If error persists are you willing to share the data confidentially?

-Liz

**Comment by yzhang88** [comment]
Hi Liz,
I update SQANTI2 to v4.0 now，and the log is:
```
R scripting front-end version 3.5.1 (2018-07-02)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /DATA/Project/mouse_check/test_OC_1
_2/collapse/OC_1_2.collapsed.rep.renamed.fasta
Error corrected FASTA /DATA/Project/mouse_check/test_OC_1_2/annotation/OC_1_2
.collapsed.rep.renamed_corrected.fasta already exists. Using it...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Can't exec "/DATA/software/SQANTI2_40/utilities/gmst/probuild": Permission de
nied at /DATA/software/SQANTI2_40/utilities/gmst/gmst.pl line 952.
GeneMarkS: error on last system call, error code -1
Abort program!!!
**** Running SQANTI...
**** Parsing provided files....
Reading genome fasta /DATA/database/mm10/reference/mm10.sort.fa....
**** Predicting ORF sequences...
Traceback (most recent call last):
  File "/DATA/software/SQANTI2/sqanti_qc2.py", line 1762, in <module>
    main()
  File "/DATA/software/SQANTI2/sqanti_qc2.py", line 1758, in main
    run(args)
  File "/DATA/software/SQANTI2/sqanti_qc2.py", line 1383, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/DATA/software/SQANTI2/sqanti_qc2.py", line 553, in correctionPlusORF
pred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/DATA/anaconda2/envs/rna/lib/python2.7/subprocess.py", line 190, in c
heck_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /DATA/software/SQANTI2_40/utilit
ies/gmst/gmst.pl -faa --strand direct --fnn --output /DATA/Project/mouse_chec
k/test_OC_1_2/annotation/GMST/GMST_tmp /DATA/Project/mouse_check/test_OC_1_2/
annotation/OC_1_2.collapsed.rep.renamed_corrected.fasta' returned non-zero exit status 1
yhrun: error: cn7047: task 0: Exited with exit code 1
```

Y.Zhang

**Comment by Magdoll** [comment]
Hi @yzhang88 ,

You have permission issues with `gmst.pl`. please fix that.

--Liz
