### ISSUE TITLE
error in --is_fusion

### ISSUE THREAD

**Issue by prometheusloong** [Magdoll/SQANTI2#45]
when i use --is_fudion, get this error.
the fasta file is from fusion_finder.py
`python sqanti_qc2.py saf.fusion.rep.fa saf.gff3 genome.fasta --aligner_choice=minimap2 --is_fusion`
if i use --is_fusion, it won't run ORFs predicted, but the next step maybe use the *.genePred?
```
R scripting front-end version 3.5.1 (2018-07-02)
[M::mm_idx_gen::44.284*0.97] collected minimizers
[M::mm_idx_gen::75.330*0.98] sorted minimizers
[M::main::75.345*0.98] loaded/built the index for 12 target sequence(s)
[M::mm_mapopt_update::77.569*0.98] mid_occ = 905
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 12
[M::mm_idx_stat::79.243*0.98] distinct minimizers: 79003367 (55.73% are singletons); average occurrences: 4.578; average spacing: 2.923
[M::worker_pipeline::81.420*0.98] mapped 99 sequences
[M::main] Version: 2.17-r943-dirty
[M::main] CMD: minimap2 -ax splice --secondary=no -C5 -uf -t 1 /public/home/genome/genome.fasta /public/home/saf.fusion.rep.renamed.fasta
[M::main] Real time: 81.481 sec; CPU: 79.892 sec; Peak RSS: 7.007 GB
/public/home/saf.gff3 doesn't appear to be a GTF file (GFF not supported by this program)
WARNING: Currently if --is_fusion is used, no ORFs will be predicted.
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /public/home/saf.fusion.rep.renamed.fasta
output written to 
WARNING: Skipping ORF prediction because user requested it. All isoforms will be non-coding!
WARNING: All input isoforms were predicted as non-coding
Traceback (most recent call last):
  File "/public/home/software/SQANTI2-master/sqanti_qc2.py", line 1794, in <module>
    main()
  File "/public/home/software/SQANTI2-master/sqanti_qc2.py", line 1790, in main
    run(args)
  File "/public/home/software/SQANTI2-master/sqanti_qc2.py", line 1418, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
  File "/public/home/software/SQANTI2-master/sqanti_qc2.py", line 625, in reference_parser
    for r in genePredReader(referenceFiles):
  File "/public/home/zcyu/software/SQANTI2-master/sqanti_qc2.py", line 124, in __init__
    self.f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/code/refAnnotation_saf.fusion.rep.genePred'
```

**Comment by Magdoll** [comment]
Hi @prometheusloong ,

I will look into this issue. Thanks for reporting.

**Comment by Magdoll** [comment]
Hi @prometheusloong ,

I've updated SQANTI2 to work with `--is_fusion` which will only work if you supply a GTF instead of FASTA/FASTQ as input. The reason being different aligners and parameters can have very different fusion alignments, so I'm going to enforce that SQANTI2 only work with fusions after the genomic coordinates have been locked down and supplied as a GTF.

The new version of SQANTI2 is v5.1.0. Let me know if this works for you.

--Liz

**Comment by prometheusloong** [comment]
Hi Liz,
Thanks for your update, it works now. And i found my task reported error because i used gff ref_annotation instead of gtf.
```
[M::main] Real time: 81.481 sec; CPU: 79.892 sec; Peak RSS: 7.007 GB
/public/home/saf.gff3 doesn't appear to be a GTF file (GFF not supported by this program)
WARNING: Currently if --is_fusion is used, no ORFs will be predicted.
```
