### ISSUE TITLE
error in sqanti_1c2.py

### ISSUE THREAD

**Issue by Trandamere** [Magdoll/SQANTI2#5]
Hi:
```
[luping@centos split-F-gene]$ python /disk/luping/tools/SQANTI2-master/sqanti_qc2.py -t 15 -g ISO-fusion.collapsed.gtf Fusarium_graminearum.RR1.41.chr.gtf ph1.fasta
R scripting front-end version 3.5.1 (2018-07-02)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /disk/luping/bam/iso-bam/pb-cluster-hqlq-total/two-condition/split-F-gene/ISO-fusion.collapsed.renamed.fasta
Traceback (most recent call last):
  File "/disk/luping/tools/SQANTI2-master/sqanti_qc2.py", line 1395, in <module>
    main()
  File "/disk/luping/tools/SQANTI2-master/sqanti_qc2.py", line 1384, in main
    if args.aligner_choice == "minimap2":
AttributeError: 'Namespace' object has no attribute 'aligner_choice'
[luping@centos split-F-gene]$ minimap2 --version
2.14-r894-dirty
```
What's wrong with this?

**Comment by Trandamere** [comment]
It‘ can run in sqanti_qc.py
```
python /disk/luping/tools/SQANTI_Source_Code/sqanti_qc.py  -t 15 -g ISO-fusion.collapsed.gtf Fusarium_graminearum.RR1.41.chr.gtf ph1.fasta

**** Running SQANTI...

**** Parsing provided files...

Skipping aligning of sequences because gtf file was provided.

Indels will be not calculated since you ran SQANTI without alignment step (SQANTI with gtf format as transcriptome input).

**** Predicting ORF sequences...

**** Parsing Reference Transcriptome...

**** Parsing Isoforms...

Splice Junction Coverage files not provided.

**** Performing Classification of Isoforms...

Number of classified isoforms 55567

**** RT-switching computation...

Full-length read abundance files not provided.

Isoforms expression files not provided.

**** Writing output files...

**** Generating SQANTI report...
Warning: Ignoring unknown aesthetics: stat
null device 
          1 
[1] "SQANTI report successfully generated!"
287.92987895

```

**Comment by Magdoll** [comment]
Hi,

You need to supply the `--aligner_choice=minimap2` option for `sqanti_qc2.py`.

--Liz
