### ISSUE TITLE
FileNotFoundError: missing refAnnotation_***.genePred file?

### ISSUE THREAD

**Issue by rebailey** [Magdoll/SQANTI2#65]
Hi @Magdoll,

I'm trying to analyze my _Brassica napus_ IsoSeq data (after running Cupcake) and I have run into this error and I can't discern how to fix it: 

```
[M::mm_idx_gen::23.105*1.89] collected minimizers
[M::mm_idx_gen::33.622*2.32] sorted minimizers
[M::main::33.623*2.32] loaded/built the index for 41 target sequence(s)
[M::mm_mapopt_update::37.394*2.19] mid_occ = 364
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 41
[M::mm_idx_stat::40.508*2.10] distinct minimizers: 76667946 (47.44% are singletons); average occurrences: 3.289; average spacing: 3.372
[M::worker_pipeline::51.177*2.44] mapped 8250 sequences
[M::main] Version: 2.13-r850
[M::main] CMD: minimap2 -ax splice --secondary=no -C5 -uf -t 10 /scratch/rbailey/isoseq/isoseq_data/sqanti2/normal_test_run/Brassica_napus_v4.1.chromosomes.fa /scratch/rbailey/isoseq/isoseq_data/sqanti2/normal_test_run/normal.collapsed.min_fl_10.filtered.rep.renamed.fasta
[M::main] Real time: 51.740 sec; CPU: 125.189 sec; Peak RSS: 9.215 GB
/scratch/rbailey/isoseq/isoseq_data/sqanti2/normal_test_run/Brassica_napus.annotation_v5.gtf doesn't appear to be a GTF file (GFF not supported by this program)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /scratch/rbailey/isoseq/isoseq_data/sqanti2/normal_test_run/normal.collapsed.min_fl_10.filtered.rep.renamed.fasta
output written to
Traceback (most recent call last):
  File "/home/rbailey/scratch/isoseq/isoseq_data/sqanti2/sqanti_qc2.py", line 2198, in <module>
    main()
  File "/home/rbailey/scratch/isoseq/isoseq_data/sqanti2/sqanti_qc2.py", line 2191, in main
    run(args)
  File "/home/rbailey/scratch/isoseq/isoseq_data/sqanti2/sqanti_qc2.py", line 1657, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
  File "/home/rbailey/scratch/isoseq/isoseq_data/sqanti2/sqanti_qc2.py", line 661, in reference_parser
    for r in genePredReader(referenceFiles):
  File "/home/rbailey/scratch/isoseq/isoseq_data/sqanti2/sqanti_qc2.py", line 129, in __init__
    self.f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/rbailey/isoseq/isoseq_data/sqanti2/refAnnotation_normal.collapsed.min_fl_10.filtered.rep.genePred'
```

It seems to be looking for a file that has not been written yet? I wondered if it was an issue with gtfToGenePred, but I've checked and it is correctly located in my $PATH.

Here is the command that results in the error:

```
python /home/rbailey/scratch/isoseq/isoseq_data/sqanti2/sqanti_qc2.py normal.collapsed.min_fl_10.filtered.rep.fq Brassica_napus.annotation_v5.gtf Brassica_napus_v4.1.chromosomes.fa
```

I've also noticed that further up in the log it doesn't seem to like the gtf file (it thinks it's a GFF file?). Here are the first few lines of the GTF file I'm using, does it seem in order?

```
chrA01	GazeA2	exon	831	1437	7.80	+	.	transcript_id "BnaA01g00010D";
chrA01	GazeA2	CDS	1070	1345	.	+	0	transcript_id "BnaA01g00010D";
chrA01	GazeA2	exon	1487	2124	2.15	-	.	transcript_id "BnaA01g00020D";
chrA01	GazeA2	exon	2256	2436	3.19	-	.	transcript_id "BnaA01g00020D";
chrA01	GazeA2	CDS	1645	2124	.	-	0	transcript_id "BnaA01g00020D";
chrA01	GazeA2	CDS	2256	2282	.	-	0	transcript_id "BnaA01g00020D";
chrA01	GazeA2	exon	2665	3177	4.45	-	.	transcript_id "BnaA01g00030D";
chrA01	GazeA2	exon	3258	3394	15.73	-	.	transcript_id "BnaA01g00030D";
chrA01	GazeA2	exon	3477	3665	30.73	-	.	transcript_id "BnaA01g00030D";
chrA01	GazeA2	exon	3712	3743	-1.00	-	.	transcript_id "BnaA01g00030D";
```

Any help would be greatly appreciated, thanks in advance!

Cheers,

Ryan

**Comment by Magdoll** [comment]
Hi @rebailey ,

This error is indicating it has trouble converting your reference GTF `Brassica_napus.annotation_v5.gtf` into .genePred format, for one reason or another.

Try running from command line:
```
gtfToGenePred \
    -genePredExt -allErrors -ignoreGroupsWithoutExons \
     Brassica_napus.annotation_v5.gtf\
     test.genePred
```

This is pretty much the command that SQANTI2 runs to convert the annotation GTF to genePred format.
-Liz

**Comment by rebailey** [comment]
Hi @Magdoll,

Thanks for your response. After running the command you provided I still get a similar error:

```
Brassica_napus.annotation_v5.gtf doesn't appear to be a GTF file (GFF not supported by this program)
```

The GTF annotation file I'm using (a few lines posted above for reference) came from a GFF to GTF conversion using gffread. To my eye it seems to be in the correct format that SQANTI2 is expecting. Any tips to get around this, or is it possible the conversion didn't actually work properly?

Thanks again!

- Ryan

**Comment by rebailey** [comment]
Update:

I was able to run gtfToGenePred successfully using a new GTF file which I converted from an updated GFF3 annotation (a sorted/fixed version of the original, made by a colleague).  

Running sqanti_qc2.py now and will update.

Thanks again for the assistance!

Cheers,
Ryan
